---
# tasks file for kub_slave
- name: Install docker and iproute-tc
  package:
    name: 
    - docker
    - iproute-tc
    state: present
- name: Configure Yum repo for kub
  yum_repository:
    description: Yum 
    name: kubernetes
    baseurl: https://packages.cloud.google.com/yum/repos/kubernetes-el7-\$basearch
    enabled: yes
    gpgcheck: yes
    gpgkey: https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
    repo_gpgcheck: yes
    exclude:
    - kubelet
    - kubeadm
    - kubectl

- name: Install kubeadm
  yum:
    name: kubeadm
    disable_excludes: kubernetes

- name: Enable docker and kubelet services
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - kubelet
    - docker

- name: Copy content of the daemon.json file
  copy:
    dest: /etc/docker/daemon.json
    src: daemon.json

- name: Restart Docker service
  service:
    name: docker
    state: restarted

- name: Copy k8s.conf file
  copy:
    dest: /etc/sysctl.d/k8s.conf
    src: k8s.conf

- name: Restart sysctl
  shell: "sysctl --system"

- name: Slaves joining to Master Node
  shell: "{{ master_token  }}"
  ignore_errors: yes
  register: init

- debug:
    var: init.stdout_lines
